version: '3.4'

services:
  dreamnekos.api:
    image: ${DOCKER_REGISTRY-}dreamnekosapi
    ports:
      - "${APP_CONTAINER_PORT}:8080"
    depends_on:
        - "postgres_db"
    build:
      context: .
      dockerfile: DreamNekos.API/Dockerfile

  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local