name: Deploy

on:
  push:
    branches: [ main ]

jobs:
   build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      env:
         REPOSITORY_NAME: ${{ github.repository }}
         REPOSITORY_NAME_FULL: ${{ github.repository }}.git
         DB_NAME: ${{ secrets.APP_DB_NAME }}
         DB_USERNAME:  ${{ secrets.APP_DB_USER }}
         DB_PASSWORD:  ${{ secrets.APP_DB_PASSWORD }}
         PROJECT_NAME: dream-nekos-connect
      with:
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        envs: REPOSITORY_NAME, REPOSITORY_NAME_FULL, DB_NAME, DB_USERNAME, DB_PASSWORD, PROJECT_NAME
        script:  |
          cd ~/Dockers/githubaction
          FOLDER_NAME=$(basename "$REPOSITORY_NAME")
          if [ -d "$FOLDER_NAME" ]
          then
            echo "Exist!"
          else
            git clone git@github.com:$REPOSITORY_NAME_FULL
            echo "Clone repository!"
          fi
          cd $FOLDER_NAME
          git pull
          echo "Updated!"
          docker compose -p $PROJECT_NAME up --force-recreate
          echo "Container run!"
