name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Docker swarm
      uses: sulthonzh/docker-remote-deployment-action@v1
      with:
        remote_docker_host: ${{ secrets.DEPLOY_HOST }}
        ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: ~/Dockers
        stack_file_name: docker-compose.yaml
        keep_files: 5
        args: my_applicaion
