name: Deploy

on:
  push:
    branches: [ main ]

jobs:
   build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      env: 
         REPOSITORY_NAME: ${{ github.repository }}.git
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        envs: REPOSITORY_NAME
        script:  |
          cd ~/Dockers/githubaction
          git clone git@github.com:$REPOSITORY_NAME
        # script:  |
        #   cd ~/Dockers/githubaction
        #   if [ -d basename $REPOSITORY_NAME ]; then
        #     rm -f -r basename $REPOSITORY_NAME
        #   else
        #     git clone git@github.com:$REPOSITORY_NAME
