name: Deploy

on:
  push:
    branches: [ main ]

jobs:
   build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      env:
         REPOSITORY_NAME: ${{ github.repository }}
         REPOSITORY_NAME_FULL: ${{ github.repository }}.git
      with:
        # host: ${{ secrets.DEPLOY_HOST }}
        # username: ${{ secrets.DEPLOY_USERNAME }}
        # key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        # envs: REPOSITORY_NAME_
        # script:  |
        #   cd ~/Dockers/githubaction
        #   git clone git@github.com:$REPOSITORY_NAME_FULL
        # script:  |
        #   cd ~/Dockers/githubaction
        #   FOLDER_NAME=$(basename "$REPOSITORY_NAME")
        #   echo $REPOSITORY_NAME_FULL
        #   if [ -d "$FOLDER_NAME" ]
        #   then
        #     rm -rf "$FOLDER_NAME"
        #   else
        #     git clone git@github.com:$REPOSITORY_NAME_FULL
        #   fi

        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        envs: REPOSITORY_NAME
        script:  |
          cd ~/Dockers/githubaction
          git clone git@github.com:$REPOSITORY_NAME
