name: Deploy

on:
  push:
    branches: [ main ]

jobs:
   build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script:  |
          cd ~/Dockers/githubaction
          git clone git@github.com:${{ env.GITHUB_REPOSITORY }}.git
